# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Exploring the web
year: 2015
description: > # this means to ignore newlines until "baseurl:"
  I'm writing cool stuff here.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://kristoforusrp.github.io" # the base hostname & protocol for your site
author: kristoforusrp
twitter_username: kristoforusrp
github_username:  kristoforusrp

# Build settings
markdown: kramdown
